### ISSUE TITLE
Administración de la organización CHWlibre

### ISSUE THREAD

**Issue by serncl** [chwlibre/iptv#3]
Desde el 5 de Julio el equipo que tiene todos los permisos del mundo mundial es el siguiente:
- @hjorgemsc 
- @Riseandfallxxx 
- @raditzlol 
- @oesj1977 
- @casterchw 
- @carlosriosg 
- @serncl 

Así que les pediría que si hay más gente interesa en unirse por el foro en CHW, los agreguen ustedes al team ["chwarianos"](https://github.com/orgs/chwlibre/teams/chwarianos).

Igual si quieren jugar con crear otros repositorios y esas cosas... vos dale, tienen/tenemos permisos totales. Eso, saludos!!

**Comment by Jorgelig** [comment]
Error 404: /orgs/chwlibre/teams/chwarianos

**Comment by serncl** [comment]
Sólo tienen permisos los usuarios listados arriba @Jorgelig. Saludos.

**Comment by Jorgelig** [comment]
Este canal ya no funciona o hay que ponerle algun codec especial al VLC?
=======================
Your input can't be opened:
VLC is unable to open the MRL 'http://movilstream.digitalproserver.com/redtv/redtvvivo/redtv.smil/chunklist-b1564000.m3u8
'. Check the log for details.
=======================

**Comment by serncl** [comment]
@Jorgelig pregúntalo en el foro o abre un nuevo issue, estás desvirtuando el propósito de este hilo amigo. Saludos.
